permalink: "/:year/:month/:title.html"
title: "2degrees Developers"
description: "This is the development blog by the developers behind 2degrees."
baseurl: 'http://dev.2degreesnetwork.com/'
safe: true
lsi: false
highlighter: rouge
gems:
- jekyll-redirect-from
sass:
    style: compressed
