permalink: "/:year/:month/:title.html"
title: "2degrees Developers"
description: "Development blog by the developers behind 2degrees, the world leading online community for sustainability professionals."
baseurl: 'http://dev.2degreesnetwork.com/'
safe: true
lsi: false
markdown: redcarpet
highlighter: pygments
gems:
- jekyll-redirect-from
